; CreditsTextPointers indexes (see data/credits/credits_text.asm)
	const_def
	const CRED_SLOGAN         ; $00
	const CRED_STAFF          ; $01
	const CRED_TAJIRI         ; $02
	const CRED_TA_OOTA        ; $03
	const CRED_MORIMOTO       ; $04
	const CRED_WATANABE       ; $05
	const CRED_MASUDE         ; $06
	const CRED_NISINO         ; $07
	const CRED_SUGIMORI       ; $08
	const CRED_NISHIDA        ; $09
	const CRED_MIYAMOTO       ; $0A
	const CRED_KAWAGUCHI      ; $0B
	const CRED_ISHIHARA       ; $0C
	const CRED_YAMAUCHI       ; $0D
	const CRED_ZINNAI         ; $0E
	const CRED_HISHIDA        ; $0F
	const CRED_SAKAI          ; $10
	const CRED_YAMAGUCHI      ; $11
	const CRED_YAMAMOTO       ; $12
	const CRED_TANIGUCHI      ; $13
	const CRED_NONOMURA       ; $14
	const CRED_FUZIWARA       ; $15
	const CRED_MATSUSIMA      ; $16
	const CRED_TOMISAWA       ; $17
	const CRED_KAWAMOTO       ; $18
	const CRED_KAKEI          ; $19
	const CRED_TSUCHIYA       ; $1A
	const CRED_TA_NAKAMURA    ; $1B
	const CRED_YUDA           ; $1C
	const CRED_MON            ; $1D
	const CRED_DIRECTOR       ; $1E
	const CRED_PROGRAMMERS    ; $1F
	const CRED_CHAR_DESIGN    ; $20
	const CRED_MUSIC          ; $21
	const CRED_SOUND_EFFECTS  ; $22
	const CRED_GAME_DESIGN    ; $23
	const CRED_MONSTER_DESIGN ; $24
	const CRED_GAME_SCENE     ; $25
	const CRED_PARAM          ; $26
	const CRED_MAP            ; $27
	const CRED_TEST           ; $28
	const CRED_SPECIAL        ; $29
	const CRED_PRODUCERS      ; $2A
	const CRED_PRODUCER       ; $2B
	const CRED_EXECUTIVE      ; $2C
	const CRED_TAMADA         ; $2D
	const CRED_SA_OOTA        ; $2E
	const CRED_YOSHIKAWA      ; $2F
	const CRED_TO_OOTA        ; $30
	const CRED_US_STAFF       ; $31
	const CRED_US_COORD       ; $32
	const CRED_TILDEN         ; $33
	const CRED_KAWAKAMI       ; $34
	const CRED_HI_NAKAMURA    ; $35
	const CRED_GIESE          ; $36
	const CRED_OSBORNE        ; $37
	const CRED_TRANS          ; $38
	const CRED_OGASAWARA      ; $39
	const CRED_IWATA          ; $3A
	const CRED_IZUSHI         ; $3B
	const CRED_HARADA         ; $3C
	const CRED_MURAKAWA       ; $3D
	const CRED_FUKUI          ; $3E
	const CRED_CLUB           ; $3F
	const CRED_PAAD           ; $40
DEF NUM_CRED_STRINGS EQU const_value

	const_def -1, -1
	const CRED_TEXT_FADE_MON ; $FF
	const CRED_TEXT_MON      ; $FE
	const CRED_TEXT_FADE     ; $FD
	const CRED_TEXT          ; $FC
	const CRED_COPYRIGHT     ; $FB
	const CRED_THE_END       ; $FA
